quarkus.package.jar.type=uber-jar

# Cache
quarkus.cache.enabled=true
quarkus.cache.caffeine.initial-capacity=1000
quarkus.cache.caffeine.maximum-size=5000

# Enables logging to file
quarkus.log.file.enable=true
quarkus.log.file.path=logs/thermostat-enhancer.log
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=false

quarkus.smallrye-openapi.enable=true
quarkus.swagger-ui.always-include=true

# eliminate false positives related to produced beans via BrandServiceProducer
quarkus.arc.remove-unused-beans=framework

# Tado APIs
quarkus.rest-client.tado-auth-service.url=https://login.tado.com
quarkus.rest-client.tado-controller-service.url=https://my.tado.com

# Tado auth config - uses OAuth2 Device Authorization Grant (RFC 8628)
# public configs: https://support.tado.com/en/articles/8565472-how-do-i-authenticate-to-access-the-rest-api
tado.auth.client-id=1bb50063-6b0c-4d11-bd99-387f4a91cc46
tado.auth.device-code-grant-type=urn:ietf:params:oauth:grant-type:device_code
tado.auth.refresh-token-grant-type=refresh_token
tado.auth.scope=offline_access

# Polling config
thermostat.polling.delay.seconds=5
thermostat.polling.expire.minutes=60